"""
Shared config loader for Hevy Coach scripts.

Config resolution order (highest priority first):
  1. config.json  — the main config file generated by install.sh
  2. environment variables  — override for power users / containers
  3. defaults

Both detect and analyze scripts import this module. The config file is
searched in a few well-known locations (see CONFIG_CANDIDATES); scripts
should also work when invoked from a directory that contains config.json.
"""

import json
import os
from pathlib import Path

# --- Defaults -------------------------------------------------------------

BASE_URL = "https://api.hevyapp.com"

DEFAULTS = {
    "hevy_api_key": "",

    "telegram": {
        "bot_token": "",
        "channel_id": "",      # numeric ID or @username
        "thread_id": None,     # Telegram topic/thread ID (optional)
    },

    "paths": {
        # Where state files live. install.sh fills these with harness paths.
        "pending_file": "hevy_pending.json",
        "last_workout_file": "hevy_last_workout.txt",
        "routines_file": "hevy_routines.json",
    },

    "coach": {
        "enabled": True,
        "poll_interval_minutes": 15,
        # Command fired by the detect script to trigger the analysis step.
        # Harness-specific. Hermes example:  hermes cron run <analyze_job_id>
        # OpenClaw users set this to their own scheduled-task trigger.
        "trigger_command": "",
    },

    "timezone": "Asia/Jakarta",
}

# --- Config file discovery ------------------------------------------------

CONFIG_CANDIDATES = [
    Path("config.json"),
    Path(os.environ.get("HEVY_CONFIG", "")),
    # config.json sitting next to the scripts (primary install location)
    Path(__file__).resolve().parent / "config.json",
    Path.home() / ".hevy" / "config.json",
    Path.home() / ".config" / "hevy-workouts" / "config.json",
    Path(os.environ.get("HERMES_HOME", str(Path.home() / ".hermes"))) / "shared" / "hevy-coach" / "config.json",
]

# --- Env var mapping ------------------------------------------------------
# Maps config key -> env var name for the fallback layer.

ENV_MAP = {
    "hevy_api_key": "HEVY_API_KEY",
    "telegram.bot_token": "TELEGRAM_BOT_TOKEN",
    "telegram.channel_id": "HEVY_COACH_CHANNEL",
    "telegram.thread_id": "HEVY_COACH_THREAD_ID",
    "coach.trigger_command": "HEVY_COACH_TRIGGER",
    "paths.pending_file": "HEVY_PENDING_FILE",
    "paths.last_workout_file": "HEVY_LAST_WORKOUT_FILE",
    "paths.routines_file": "HEVY_ROUTINES_FILE",
}


def _deep_merge(base, override):
    """Recursively merge override into a copy of base (override wins)."""
    out = dict(base)
    for k, v in (override or {}).items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def load_config() -> dict:
    """Load config from file (if present) + env fallbacks + defaults."""
    cfg = json.loads(json.dumps(DEFAULTS))  # deep copy of defaults

    # 1. config.json file
    found = None
    for cand in CONFIG_CANDIDATES:
        if cand and Path(cand).is_file():
            found = Path(cand)
            break
    if found:
        try:
            cfg = _deep_merge(cfg, json.loads(found.read_text()))
        except (json.JSONDecodeError, OSError):
            pass  # corrupt config — fall through to defaults/env

    # 2. env var overrides (flattened key -> env)
    def set_nested(d, dotted_key, value):
        parts = dotted_key.split(".")
        cur = d
        for p in parts[:-1]:
            cur = cur.setdefault(p, {})
        cur[parts[-1]] = value

    for dotted, env in ENV_MAP.items():
        val = os.environ.get(env)
        if val is not None and val != "":
            set_nested(cfg, dotted, val)

    # Normalize numeric fields
    try:
        if cfg["telegram"]["thread_id"] is not None:
            cfg["telegram"]["thread_id"] = int(cfg["telegram"]["thread_id"])
    except (ValueError, TypeError):
        pass
    try:
        cfg["coach"]["poll_interval_minutes"] = int(cfg["coach"]["poll_interval_minutes"])
    except (ValueError, TypeError):
        pass

    return cfg


def resolve_path(cfg: dict, key: str) -> Path:
    """Resolve a state-file path from config, expanding ~ and making absolute."""
    raw = cfg.get("paths", {}).get(key, "")
    if not raw:
        return Path(raw)
    p = Path(raw).expanduser()
    if not p.is_absolute():
        p = Path.cwd() / p
    return p
